pass tasks 02
js-tasks-ru/js-20230223_localbody pull request #2
Opened 2023-03-01 14:51 UTC by localbody

в двух последних задачах считерствовал - использовал delete

2023-03-01 14:51 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-02 12:09 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  return arr.concat().sort(compareStrings)
более современный способ копировать массив:
```js
const copy = [...arr]
```

2023-03-02 12:09 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    .forEach((field) => delete newObj[field])
использовать `delete` в связке с объектом не рекомендуется, ведь копирование объекта `{...obj}` делает `shallow copy` или другими словами неглубокую копию, поэтому удаление может привести к весьма неожиданным последствиям

2023-03-02 12:10 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const newObj = Object.assign({}, obj)
более современный способ копировать объект:
```js
const copy = {...obj};
```

2023-03-02 12:11 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    .forEach((field) => delete obj[field])
подумайте, можно ли обойтись без `delete`

2023-03-02 12:11 UTC, dosandk requested changes
пожалуйста поправьте решения `pick/omit`

2023-03-02 12:46 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-02 12:47 UTC, localbody commented
rewrite !

2023-03-04 06:27 UTC, localbody commented
rewrite tasks 02

2023-03-04 06:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-03-04 06:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-03-05 11:13 UTC, dosandk approved these changes
good 👍

2023-03-05 11:13 UTC, merged